# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  upload-artifacts:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 16
          
      - name: install dependencies
        run: npm install
        
      - name: Build
        run: npm run make
        
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: electron-app-${{ matrix.os }}
          path: out/*
  
  publish:
    needs: upload-artifacts
    
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    steps:
      - name: Download install files
        uses: actions/download-artifact@v2
        with:
          name: electron-app-${{ matrix.os }}
      
      - name: Zip up needed files
        run: |
          zip -r windows.zip . -i electron-app-windows-latest/electron-app-win32-x64/
          zip -r linux.zip . -i electron-app-ubuntu-latest/electron-app-linux-x64/
          zip -r mac.zip . -i electron-app-macos-latest/electron-app-darwin-x64/
          
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            windows.zip
            linux.zip
            mac.zip
